source 'https://rubygems.org'
ruby '2.6.5'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'airbrake'
gem 'aws-sdk'
gem 'bootstrap-sass'
gem 'bootstrap-wysihtml5-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'coffee-rails'
gem 'colorize'
gem 'compass-rails'
gem 'country_select'
gem 'devise'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'kramdown'
gem 'localer'
gem 'mini_magick'
gem 'momentjs-rails'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'nprogress-rails'
gem 'paperclip'
gem 'pg'
gem 'premailer-rails'
gem 'puma'
gem 'rails', '< 6'
gem 'rakismet'
gem 'sass-rails'
gem 'simple_form'
gem 'slim-rails'
gem 'split', require: 'split/dashboard'
gem 'textacular'
gem 'uglifier'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

group :development do
  gem 'annotate'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'figaro'
  gem 'letter_opener'
  gem 'meta_request'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-rails'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'database_cleaner'
  gem 'faker' # Generates names, emails and other placeholders for factories
  gem 'launchy'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'timecop'
end
