development:
  adapter: postgresql
  database: opensit_development
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  timeout: 5000
  username: <%= `whoami`.chomp %>

test:
  adapter: postgresql
  database: opensit_test
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  timeout: 5000
  username: <%= `whoami`.chomp %>

production:
  adapter: postgresql
  database: opensit_production
  pool: 5
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>
